### ISSUE TITLE
Animation on Scrolling back too

### ISSUE THREAD

**Issue by abhisheksoni27** [jlmakes/scrollReveal.js#154]
The demo (aka [scrollRevealjs.org](http://www.scrollrevealjs.org) animates on scroll down, and then when scrolling back up, it animates too! Is that using this same library, and if yes, how?

**Comment by mikerockett** [comment]
https://github.com/jlmakes/scrollReveal.js/wiki/Configuration#reset

**Comment by jlmakes** [comment]
Just as @mikerockett has referenced, the `reset` property (set to `false` by default) controls whether or not revealed elements will reset when scrolled out of view.

This will override the defaults, and reset all animations (as seen on the demo):
```js
var config = {
  reset: true,
}

var sr = new scrollReveal( config );
```

This will use (or disable) reset for specific elements:
```html
<div data-sr="reset"> Foo </div>
<div data-sr="no reset"> Foo </div>
```

**Comment by abhisheksoni27** [comment]
Thanks. It works.

**Comment by madebylux** [comment]
Hello,

Thanks for your enquiry!

I'm now out of the office until Tuesday 30th June.

For urgent web hosting support, please call 0113 3185277, otherwise I will get back to you on my return.

Warm regards,
James

Lux Digital Ltd
e: james@madebylux.com
m: 07734 467977
w: www.madebylux.com
t: 0113 318 5277
a: Tower Works, Globe Road, Leeds LS11 5QG
