### ISSUE TITLE
Not compatible with Alton? (full-page scroll-jacking jQuery plugin)

### ISSUE THREAD

**Issue by esbm** [jlmakes/scrollReveal.js#164]
I combined scrollReveal.js with Alton (https://github.com/paper-leaf/alton/) to make it more playful. Unfortunately, it's very buggy and creates an inconsistent experience from browser to browser. For example, when I arrow tab from section to section on chrome (mac), nothing appears. Then scrolling doesn't work on Firefox (mac).

Here's the page: https://www.npd.com/latest-reports/longitudinal-data/

Sorry if this isn't the correct place to post this, but I was wondering if anyone has dealt with similar issues and knows of how I may be able to fix them and get it to work properly on at least modern browsers?

Thanks in advance for your help.
-Elliot

**Comment by nikola1970** [comment]
Did you try to set vFactor to lower? 0.10 for example.

window.sr = new scrollReveal({
		mobile: true,
		vFactor:  0.10   //(or 0.1)
	});

**Comment by jlmakes** [comment]
@esbm Any luck in the end?

>"Scrolljacking basically means we replace native scrolling (what you're used to) with targeted scrolling..."

Since ScrollReveal is built on scroll, particularly native browser scrolling, a scroll-jacking library may be a bit difficult to integrate with. 

After playing with the Alton demo a bit more, it doesn’t even seem to trigger traditional scroll events… I’m not sure what to recommend.
