### ISSUE TITLE
v3 and the data-sr tag attribute

### ISSUE THREAD

**Issue by JoomFX** [jlmakes/scrollreveal.js#194]
Hey @jlmakes 

Thanks for v3 but I'm kinda confused with it.
What happened to the `data-sr` tag attribute? Can't we just use the syntax we used so far:

```html
<p data-sr="enter left and move 100px over 0.5s wait 0.1s"></p>
```

As far as I understand, in v3 we need to configure the CSS classes in advance.
I mean, using the "human readable" syntax with the `data-sr` tag attr was much more flexible in my opinion. 

Have a look at the following screenshot - I'm a theme/template developer and in my framework I specifically added an option, so the user can add tag attributes on almost all HTML elements. I did it mostly because of ScrollReveal.js. With the v2.x syntax everything was simply awesome, the user was able to define the exact effect he wants using the "human readable" syntax and now, in v3, I have to define classes, but how can I know what effect the user might want, I cannot define 10s of classes with different effects... do you see what I mean when I say that v2.x and the `data-sr` syntax was much more flexible and user friendly? Anyway, here's the screenshot from my framework:

![alt](http://i.imgur.com/lcJeBXF.png)

So, will we be able to use the same `data-sr` syntax in v3? Please, please say "Yes".

```html
<p data-sr="enter left and move 100px over 0.5s wait 0.1s"></p>
```

**Comment by JoomFX** [comment]
Or if we will not be able to use the `data-sr` tag attribute in v3, with this awesome and easy syntax, then could you please send me the v2.x documentation with the keywords?

v3 and the logic behind it simply does not work in my case.

**Comment by jlmakes** [comment]
Yes, the data-sr API was removed.

You can continue to use v2.3.x, which is still [documented in the wiki](https://github.com/jlmakes/scrollreveal.js/wiki). Admittedly, I found some bugs while going through the v3.0 re-write, but for most use cases it's still a solid release.

***

If you're interested, you can fork ScrollReveal and explore an earlier commit of the 3.0 release candidate where there existed both the JavaScript API and the data-sr API.

> **Highlighted Below:** The last commit before the data-sr API was removed.

<img width="1042" alt="screen shot 2015-12-18 at 1 10 58 am" src="https://cloud.githubusercontent.com/assets/2044842/11886746/6bd6c99c-a525-11e5-8a8a-84e6150383c8.png">

**Comment by jlmakes** [comment]
Hi @JoomFX 

I appreciate your feedback.

> "What happened to the `data-sr` tag attribute? Can't we just use the syntax we used so far? As far as I understand, in v3 we need to configure the CSS classes in advance. I mean, using the "human readable" syntax with the `data-sr` tag attr was much more flexible in my opinion."

A JavaScript API was the _literally_ the first issue and feature request when ScrollReveal launched almost 2 years ago, and for good reason. I think using the `data-sr` attribute made things easy, but the flexibility was double-edged.

##### Scenario A
You have 4 elements, and you want them to reveal in a similar fashion, but with a 200ms delay between them. This becomes easy using `data-sr`—you can quickly define reveal animations, and make tweaks as needed.

When changing small things (e.g. delay) about otherwise identical reveals, Inline is quick and helpful.

##### Scenario B

Consider a 6-page website where multiple `h1`, `h2`, `p` and `img` elements use various reveals. Using `data-sr`, now your HTML is looking a little cluttered, and you potentially have over 100 places in your markup to update if you want to change things.

When managing _n1_ number of elements across _n2_ number of pages, inline is not so fun anymore.

### Sounds familiar…

This is _exactly_ the problem CSS addresses, and I think it was a natural evolution to introduce a selector based JavaScript API to ScrollReveal, to give it the same cascading power.

> *Sidebar:* The example of changing delays in Scenario A for a "sequence" effect might be common enough, that I’m considering developing some type of `config.sequence` or `sequence()` to assist in v3.1.

### But why remove data-sr /  inline?

- Almost double the file size
- Confusing documentation (e.g. rotate object, vs spin/rotate/roll keywords)
- Not all features are supported (e.g. using a custom viewport)
- Cluttered markup
- No element specific callbacks

Also, ScrollReveal 2 was unreliable with AJAX, and had very poor support for multiple viewports—all of the above amounted to a scrutinizing re-evaluation of the strategy and architecture.

> "I'm a theme/template developer and in my framework I specifically added an option, so the user can add tag attributes on almost all HTML elements. **I did it mostly because of **ScrollReveal**. With the v2.x syntax everything was simply awesome, the user was able to define the exact effect he wants using the "human readable" syntax and now, in v3, I have to define classes, but how can I know what effect the user might want, I cannot define 10s of classes with different effects... do you see what I mean when I say that v2.x and the `data-sr` syntax was much more flexible and user friendly?"

You're right, the inline approach of ScrollReveal 2 was well suited to your particular case. (See my previous post for some ideas.)

#### If you were to move to 3.0...

I think the challenge is less about how to deal with element selectors, but that the end user wouldn't be using "natural language" to create their reveals… they’d have to use JavaScript??…_No, the solution would be to develop a UI around the new JS API._ 

It would be more work, but I believe would result in a better user experience. Imagine, no syntax to learn—no matter how "natural", the syntax still has rules to be followed. Plus, there’s probably a number of options, perhaps like `easing` or `vFactor` that users may not ever use if left to master the syntax on their own.

## In The End

I’m traveling for the next few days, but I’ve been thinking about a change log / migration guide to go into these changes (and the reasons behind them)—hopefully this post can honor that end for now.

**If there’s enough demand, I would consider re-introducing the `data-sr` api into 3.0, or perhaps updating a ScrollReveal 2.4 release with some of the improvements seen in v3.0, but still without the JavaScript API.**

**Comment by JoomFX** [comment]
Hey @jlmakes ,

Thanks a lot for the detailed answer :+1: 

Now, I'd like to share some additional feedback as well...

I understand your reasons for making these changes (removing the `data-sr` API). But what do you think about putting it back in v3 :smile: I'll share my point of view with you:

1. The reason I (and many other users) fell in love with ScrollReveal.js was this exact functionality.
2. There already is a CSS class-based solution (WOW.js + Animate.css) even though it is too big in size.
3. You are completely right about the **Scenario B** above. In this case Inline is not so fun. But why remove the Inline functionality instead of keeping it and adding the JavaScript API as an additional feature?

And because of point 3 above, I'd like to comment your points about **But why remove data-sr / inline?**

>Almost double the file size

I'm all-in for having as small assets as possible. But come on, v2.3 that I'm using is 9KB! If you add the JavaScript API as an additional feature it might become 12KB. Compare this with the 65KB that WOW.js + Animate.css offers!

>Confusing documentation (e.g. rotate object, vs spin/rotate/roll keywords)

I'm not sure I agree here - the functionality and the documentation were just perfect! You Julian, did a great job here ;) None of my customers have ever complained about ScrollReveal.js, just the opposite - they all love it!

 >Not all features are supported (e.g. using a custom viewport)

Well, yeah... in this case, if the user need the feature so badly, he can just use the JavaScript API (assuming it will be added as an additional feature)
 
>Cluttered markup

Not really - if you want to animate just 3 or 4 elements (as I'm doing in my demos) it is perfectly fine. If you want to have many animated elements (with the same effect) then use the JavaScript API (assuming it will be added as an additional feature)
    
>No element specific callbacks

No comment here :smile: 

@jlmakes Julian, as a conclusion - why making ScrollReveal.js better for some users and worse for the other users, instead of extending the current functionality (adding the JavaScript API) and making it better for everybody? And once again, as mentioned above, there already is a CSS class-based solution, but there isn't really a good Tag Attribute based solution... well, there is and it is called ScrollReveal.js v2.x but you want to kill it ;)

I really hope you will consider the above. Have a great Christmas mate!

**Comment by jlmakes** [comment]
@JoomFX 

#### Scenario A in v2.3.2

Pretty straight forward sequenced reveal animation.

```css
/* CSS */
[data-sr] { visibility: hidden }
```
```html
<div data-sr="wait 0.5s"> foo </div>
<div data-sr="wait 1s"> foo </div>
<div data-sr="wait 1.5s"> foo </div>
<div data-sr="wait 2s"> foo </div>
```
```js
// JavaScript
window.sr = new scrollReveal({ delay: 'onload' });
```

#### Scenario A in v3.0

```css
/* CSS */
.reveal { visibility: hidden }
```
```html
<div class="reveal one"> foo </div>
<div class="reveal two"> foo </div>
<div class="reveal three"> foo </div>
<div class="reveal four"> foo </div>
```
```js
// JavaScript
window.sr = ScrollReveal({ delayType: 'onload' })
  .reveal( '.reveal.one',   { delay: 500  } )
  .reveal( '.reveal.two',   { delay: 1000 } )
  .reveal( '.reveal.three', { delay: 1500 } )
  .reveal( '.reveal.four',  { delay: 2000 } );
```

Even with a small example, the difference in setup is not really much different—and the benefits of the JavaScript API quickly begin to outweigh inline convenience as the complexity or number of reveals increases.

I’m definitely considering your feedback—**I knew it was a bold move to remove the `data-sr` API.** The idea I keep coming back to is inline CSS… just because it's easy to apply a few styles, it's still generally frowned upon for reasons I've already mentioned. It’s very easy to just keep adding and adding features to any product (especially javaScript libraries), but I’m actively looking for ways to evolve ScrollReveal without constantly increasing it's size and complexity.

> "I'm not sure I agree here - the functionality and the documentation were just perfect! You Julian, did a great job here ;) None of my customers have ever complained about ScrollReveal.js, just the opposite - they all love it!"

I appreciate that, I put a lot of effort into my documentation—it’s surprising how much I learn about my library in doing so. It was actually the process of trying to simply explain _two different APIs_ that really made me question the value of the inline API.

Admittedly, I was supporting both string and object base configurations inside the JavaScript API…

```js
// Demonstration
var sr = ScrollReveal( '.fooReveal', 'enter left and move 30px over 2s' );
```

In retrospect, I think this was a large part of that confusion—overlapping APIs. Hypothetically speaking, if I were to re-introduce the `data-sr` API, I think I would keep them entirely separate; first a **beginners** section outlining `data-sr` and it's use, and a **advanced** section detailing the JavaScript API.

All that said, I still am not sure it's worth encouraging messy markup and inline presentational markup in HTML… just for an few seconds saved on very simple use cases. I think your particular use case is more compelling since you're exposing the data-sr attribute to non-developers...

Moving forward, I think v3.0 is the future — but as I mentioned, I don't mind supporting ScrollReveal 2 with a few updates for legacy users who have unique use cases like yours.

**Comment by JoomFX** [comment]
@jlmakes  Thanks Julian!
It is a nice discussion indeed :wink: 

Yes, I agree with everything you are saying and if I was just building websites and apps for the end user (if I was not developing theme/templates) I would definitely go with v3.

>I put a lot of effort into my documentation—it’s surprising how much I learn about my library in doing so.

Yeah, I'm really surprised how many bugs I find and how many improvements I make while doing the documentation for my products :smile: 

>Hypothetically speaking, if I were to re-introduce the data-sr API, I think I would keep them entirely separate; first a beginners section outlining data-sr and it's use, and a advanced section detailing the JavaScript API.

To me it sounds as a great solution but I'm not sure you would want to maintain two separate libraries. If you can do that, it would be great! This will definitely be a great move as all kind of users ( and use cases) will be able to use ScrollReveal.js. The `data-sr` API has it's place for sure... as I told you earlier, there aren't other Tag Attr based solutions like yours (at least not that good and that flexible) and many users love it for that!

Anyway, now is my turn :smile: .... Hypothetically speaking, if you consider NOT to maintain two separate libraries and you give up on the `data-sr` API completely, I would like to ask you a couple of questions (yeah, I could test it myself, but... you know :smile: ):

1. I'm starting to see some good things in v3 and my particular case (I still prefer the `data-sr` API though). But in order to be able to implement it I will need to be able to group CSS classes. So my question is - is this possible:

```
<div class="reveal left delay1 distance1 duration1"> foo </div>
<div class="reveal right delay2 distance2 duration2"> foo </div>
<div class="reveal top delay3 distance3 duration3"> foo </div>
<div class="reveal rotate1 delay4 distance4 duration4"> foo </div>
```

```
// JavaScript
window.sr = ScrollReveal({ delayType: 'onload' })
  .reveal( '.reveal.delay1',   { delay: 500  } )
  .reveal( '.reveal.delay2',   { delay: 1000 } )
  .reveal( '.reveal.delay3', { delay: 1500 } )
  .reveal( '.reveal.delay4',  { delay: 2000 } )
  .reveal( '.reveal.distance1',   { distance: 20px  } )
  .reveal( '.reveal.distance2',   { distance: 40px  } )
  .reveal( '.reveal.distance3',   { distance: 60px  } )
  .reveal( '.reveal.distance4',   { distance: 80px  } )
  .reveal( '.reveal.duration1',   { duration: 200  } )
  .reveal( '.reveal.duration2',   { duration: 400  } )
  .reveal( '.reveal.duration3',   { duration: 600  } )
  .reveal( '.reveal.duration4',   { duration: 800  } )
  .reveal( '.reveal.left',   { origin: left  } )
  .reveal( '.reveal.right',   { origin: right } )
  .reveal( '.reveal.top', { origin: top } )
  .reveal( '.reveal.rotate1',  { rotate: { x: 180, y: 0, z: 0 } } );
```

If the above is possible, then I can pre-define some classes and include them in my documentation.

2. Is v3 considered stable enough so I can implement it in production straight away?

Well, one thing is for sure - I'm not replacing ScrollReveal.js with anything else! I'm thinking to stick with v2 for now but we'll see.

And thanks once again Julian, for all the help and the nice and friendly discussion :wink:

**Comment by jlmakes** [comment]
**A1**: You cannot call `reveal()` on an empty element set. Meaning, if it finds 0 elements that match that selector, it will _only_ return a warning. 

**A2**: I just released ScrollReveal v3.0.2 which is stable, and in use in a few of my own projects. However, given your particular use case, it really sounds like v2.3.2 is the best suited to your needs.

**Comment by JoomFX** [comment]
Thanks Julian.

Alright, then it will be really great if you can maintain a ScrollReveal.js version with the `data-sr` API for other users like me :wink:

**Comment by jlmakes** [comment]
@JoomFX When I have some time, I will go through 2.3.2 to see if there's any fixes/improvements I can make—but for the time being, it should be sufficient for anyone looking for the legacy `data-sr` API.

**Comment by hyosukjung** [comment]
Hi. I'm Dylan.jung.
I have been studying about srcollReveal.js recently, and I was also wondering why it doesn't work when I was using 'data-sr' attribute. Now I read your conversation( @JoomFX and @jlmakes ) and understand it. Thank you for your conversation. :)
And now I have one more question.
Where can I download the scrollReveal.js version 2.3.x?

**Comment by jlmakes** [comment]
@hyosukjung Legacy versions are right here on GitHub:
https://github.com/jlmakes/scrollreveal/tree/v2.3.2

_How you find it:_

![tags](https://user-images.githubusercontent.com/2044842/30208197-ac63b76e-9492-11e7-8f46-d058e210c133.gif)

**Comment by hyosukjung** [comment]
@jlmakes 
Thank you for you support! :)
You are very kind for giving me a very detail information.
Actually a friend of mine told me about scrollReveal.js a few days ago, so I searched about it by googling. I just have been studying by myself searching the internet.

**Comment by crazypsycho** [comment]
I don´t like to work with old versions, but i need the data-sr-api. So I have copied and change the api from 2.3 and make it workable with 3.x.

Embed my script and call initScrollRevealByData() and all elements with data-sr will be revealed. 
It has minified only 3 KB.

```
/**
 * Inits scrollReveal from data-sr attribute (like it was in scrollReveal 2.x)
 *
 * @param object defaultConfig
 */
function initScrollRevealByData(defaultConfig) {
    if (typeof(defaultConfig) == 'undefined') {
        var defaultConfig = {};
    }

    var elements = document.querySelectorAll('[data-sr]');

    if (!window.sr && elements.length) {
        window.sr = ScrollReveal(defaultConfig);
    }

    for (var index in elements) {
        if (isNaN(index)) {
            continue;
        }
        var elem = elements[index];
        var parsed = {};
        var config = {};
        var words = elem.getAttribute('data-sr').split(/[, ]+/);

        words.forEach(function(keyword, i) {
            switch(keyword) {
                case 'enter':
                    parsed.origin = words[i + 1];
                    break;

                case 'wait':
                    parsed.delay = words[i + 1].replace('s', '') * 1000;
                    break;

                case 'move':
                    parsed.move = words[i + 1];
                    break;

                case 'ease':
                    parsed.move = words[i + 1];
                    parsed.ease = 'ease';
                    break;

                case 'ease-in':
                    if (words[i + 1] == 'up' || words[i + 1] == 'down') {
                        if (words[i + 1] == 'down') {
                            parsed.scale = (100 + words[i + 2].replace('%', '')) / 100;
                        } else {
                            parsed.scale = (100 - words[i + 2].replace('%', '')) / 100;
                        }
                        parsed.easing = 'ease-in';
                        break;
                    }

                    parsed.move = words[i + 1];
                    parsed.easing = 'ease-in';
                    break;

                case 'ease-in-out':
                    if (words[i + 1] == 'up' || words[i + 1] == 'down') {
                        if (words[i + 1] == 'down') {
                            parsed.scale = (100 + words[i + 2].replace('%', '')) / 100;
                        } else {
                            parsed.scale = (100 - words[i + 2].replace('%', '')) / 100;
                        }

                        parsed.easing = 'ease-in-out';
                        break;
                    }

                    parsed.move = words[i + 1];
                    parsed.easing = 'ease-in-out';
                    break;

                case 'ease-out':
                    if (words[i + 1] == 'up' || words[i + 1] == 'down') {
                        if (words[i + 1] == 'down') {
                            parsed.scale = (100 + words[i + 2].replace('%', '')) / 100;
                        } else {
                            parsed.scale = (100 - words[i + 2].replace('%', '')) / 100;
                        }

                        parsed.easing = 'ease-out';
                        break;
                    }

                    parsed.move = words[i + 1];
                    parsed.easing = 'ease-out';
                    break;

                case 'hustle':
                    if (words[i + 1] == 'up' || words[i + 1] == 'down') {
                        if (words[i + 1] == 'down') {
                            parsed.scale = (100 + words[i + 2].replace('%', '')) / 100;
                        } else {
                            parsed.scale = (100 - words[i + 2].replace('%', '')) / 100;
                        }

                        parsed.easing = 'cubic-bezier( 0.6, 0.2, 0.1, 1 )';
                        break;
                    }
                    parsed.move = words[i + 1];
                    parsed.easing = 'cubic-bezier( 0.6, 0.2, 0.1, 1 )';
                    break;

                case 'over':
                    parsed.over = words[i + 1];
                    break;

                case 'flip':
                case 'pitch':
                    parsed.rotate = parsed.rotate || {};
                    parsed.rotate.x = words[i + 1];
                    break;

                case 'spin':
                case 'yaw':
                    parsed.rotate = parsed.rotate || {};
                    parsed.rotate.y = words[i + 1];
                    break;

                case 'roll':
                    parsed.rotate = parsed.rotate || {};
                    parsed.rotate.z = words[i + 1];
                    break;

                case 'reset':
                    if (words[i - 1] == 'no') {
                        parsed.reset = false;
                    } else {
                        parsed.reset = true;
                    }
                    break;

                case 'scale':
                    if (words[i + 1] == 'down') {
                        parsed.scale = (100 + words[i + 1].replace('%', '')) / 100;
                    } else if (words[i + 1] == 'up') {
                        parsed.scale = (100 - words[i + 2].replace('%', '')) / 100;
                    } else {
                        parsed.scale = (100 - words[i + 1].replace('%', '')) / 100;
                    }

                    if (parsed.scale == 0) {
                        parsed.scale = 0.01;
                    }
                    break;

                case 'vFactor':
                case 'vF':
                    parsed.vFactor = words[i + 1];
                    break;

                case 'opacity':
                    parsed.opacity = words[i + 1];
                    break;

                default:
                    return;
            }
        });

        // Build default config object, then apply any keywords parsed from the
        // data-sr attribute.
        config = defaultConfig;

        for (var key in parsed) {
            config[key] = parsed[key];
        }

        // Let’s make sure our our pixel distances are negative for top and left.
        // e.g. "enter top and move 25px" starts at 'top: -25px' in CSS.
        if (config.origin === 'top' || config.origin === 'left') {
            config.move = '-' + config.move;
        }

        sr.reveal(elem, config);
    }
}
```
