### ISSUE TITLE
Sequenced Animations

### ISSUE THREAD

**Issue by atilkan** [jlmakes/scrollreveal.js#215]
I am sorry, i am aware this is not the correct place, i don't know where is.
As i see there is not an option to set delay between multiple elements. So a gap would be a nice option.
When element count more than 1, delay between each element.
for ex:
`delayBetween: 0.20`
I am exploring the code but it would take too much time for me to figure out.

Thanks.

p.s. One more thing please. If element doesn't exist don't throw error.

**Comment by atilkan** [comment]
One more thing please. If element doesn't exist don't throw error.

**Comment by jlmakes** [comment]
Hey @atilkan, this is already on my mind and has been requested! See #187 

The use case of animating an element set in a sequence, instead of manually setting delays, is definitely the next major feature I am working on for ScrollReveal.

>p.s. One more thing please. If element doesn't exist don't throw error.

For this, you could easily clone the repository, run `npm install`, remove the `console.warn` from [line 77](https://github.com/jlmakes/scrollreveal.js/blob/master/scrollreveal.js#L77) in the `scrollreveal.js` source, and run `gulp build` to generate new `dist/scrollreveal.js` and `dist/scrollreveal.min.js` files.

**Comment by atilkan** [comment]
I am really aware delay sequence is harder than it looks. I looked at the source.
Thanks. Great job. Have a nice day.

**Comment by jlmakes** [comment]
@atilkan I removed the `console.warn` from `v3.0.8` and actually a few other improvements to ensure ScrollReveal performs better under less than ideal situations.

I’m still working on a `sequence()` method :bow:

**Comment by atilkan** [comment]
You sir are fast.

**Comment by atilkan** [comment]
When you do sequencing, I will be more than just scroll reveal. 
greensock.com check.

**Comment by jlmakes** [comment]
### New In ScrollReveal v3.1
You can now pass a sequence interval (in milliseconds) to the `reveal()` method, making sequenced animations a breeze.
```js
// interval passed to reveal
window.sr = ScrollReveal({ duration: 2000 });
sr.reveal('.box', 50);

// or...

// interval and custom config passed to reveal
window.sr = ScrollReveal();
sr.reveal('.box', { duration: 2000 }, 50);
```
![sequencer](https://cloud.githubusercontent.com/assets/2044842/13556788/a7dda6c6-e3e2-11e5-93fa-d6a227cbb5dc.gif)

It was a beast to implement, but thanks for the request @atilkan :bow:

**Comment by atilkan** [comment]
Great to see. You really deserve best compliments.
