### ISSUE TITLE
config.mobile works inside constructor, but not inside reveal() calls

### ISSUE THREAD

**Issue by petravicius** [jlmakes/scrollreveal.js#216]
https://github.com/jlmakes/scrollreveal.js/issues/53 — This option seems to be gone with v3.

Also, `mobile: true/false` setting seems to only work on the default settings, but not for the individual reveal sets. I'd like to either be able to:
- Disable reveals on mobile for some sets, and working on others
- Disable delay on mobile devices (#53)

**Comment by jlmakes** [comment]
>Also, `mobile: true/false` setting seems to only work on the default settings, but not for the individual reveal sets.

Very good catch @petravicius, thank you. I’ll definitely add this in.

As far as disabling delay on mobile, let me give it a little more thought… for the time being, you should be able to add a similar snippet from #53 on [line 155](https://github.com/jlmakes/scrollreveal.js/blob/master/scrollreveal.js#L155):
```js
if ( sr.tools.isMobile() ) {
	config.delay = 0;
}
```

**Comment by petravicius** [comment]
The snippet works great. Thanks!

**Comment by jlmakes** [comment]
@petravicius I was going through the Icebox and noticed #147

And I realized, you can easily use the same method I referenced _ouside_ of the source, to customize everything you want about mobile reveals…

_Example:_
```js
window.sr = ScrollReveal();

var mobileConfig  = { delay : 500, opacity : 0.5, duration : 200 };
var desktopConfig = { delay : 0 };

if ( sr.tools.isMobile() ) {
  sr.reveal( '.fooClass', mobileConfig );
} else {
  sr.reveal( '.fooClass', desktopConfig );
}
```
I think this is a clean solution, and leaves the logic up to the user instead of cluttering the source. This means you can already customize _everything_  on mobile already. Question #172 even includes an idea on how to change configuration based on screen width, almost "media-queries for reveals."

I’m going to remove the `Feature Request` and focus on the `Fix / Improvement` you brought to my attention, with `mobile: false` not working on individual reveal sets. :bow:

**Comment by dougmacklin** [comment]
Hey @jlmakes, thanks for the `sr.tools.isMobile()` conditional suggestion, that is very helpful.

I just wanted to point out that if one of your config options is `mobile: false` and you set your scroll reveal class to `visibility: hidden` (to prevent flickering like [the docs recommend](https://github.com/jlmakes/scrollreveal.js#42-improve-user-experience)), the elements will never appear on mobile. I got around this by doing the following:

```
if ( sr.tools.isMobile() )
  $('.sr').css('visibility', 'visible');
```

It might be worth mentioning this in the docs.

**Comment by jlmakes** [comment]
Good catch @dougmacklin :bow: 

ScrollReveal returns nothing if `sr.tools.isMobile() == true` and `config.mobile == false`. But since I‘m refactoring how `config.mobile` works, I don’t think there’s any conflict with making ScrollReveal always apply `visibility: visible` to elements within a reveal set—even when on mobile but `config.mobile = false`.

Let me work on this and get back to you.

**Comment by dougmacklin** [comment]
Thanks! I think that's a great solution.

**Comment by jlmakes** [comment]
Check out `v3.0.7` @dougmacklin :bow:

I did some refactoring plus heavily commented the new version 3 source. Everything seems to work as we discussed—ScrollReveal will always apply `visibility: visible` when:
- on mobile but `config.mobile = false`.
- CSS Transform/Transition aren’t supported.

**Comment by jlmakes** [comment]
Check out `v3.0.8` @dougmacklin @petravicius :bow:

I did some refactoring plus heavily commented the new version 3 source. Everything seems to work as we discussed—ScrollReveal will always apply `visibility: visible` when:
- On mobile and `config.mobile = false`.
- CSS Transform/Transition aren’t supported.

**Comment by dougmacklin** [comment]
@jlmakes This works perfectly, thanks again!
