### ISSUE TITLE
Update on resize + option for class instead of inline styles?

### ISSUE THREAD

**Issue by xtianmiller** [jlmakes/scrollreveal.js#217]
Not really an issue, but there's a couple of features that might make this already great plugin even better.  Sorry if this has been covered before—didn't see anything in the read me!

Was wondering if it's possible to update SR on resize—when you resize browser window and a "reveal" item comes into view; it doesn't acknowledge that unless you start scrolling.

Also, what about the ability to bypass inline styling entirely (should you wish) and have a custom class added to the element instead.  That way you can set the animations through the CSS. 

Best,
Christian

**Comment by jlmakes** [comment]
Thanks @xtianmiller 

In the future, please open an issue per topic, instead of two topics in one issue like you’ve done here. It makes managing issues a lot easier :bee:

#### Update on Resize

>"Was wondering if it's possible to update SR on resize—when you resize browser window and a "reveal" item comes into view; it doesn't acknowledge that unless you start scrolling."

I’m not sure what problem you’re having—this is already supported ([line 216](https://github.com/jlmakes/scrollreveal.js/blob/master/scrollreveal.js#L216) and [220](https://github.com/jlmakes/scrollreveal.js/blob/master/scrollreveal.js#L220)):

![scrollreveal-resize](https://cloud.githubusercontent.com/assets/2044842/12226211/d5e2e55e-b818-11e5-8474-e752d3259d6f.gif)

If you can replicate a bug (recommended with [JSBin](http://jsbin.com)) than please open a separate issue for that.

#### Add Class When Visible

>"Also, what about the ability to bypass inline styling entirely (should you wish) and have a custom class added to the element instead.  That way you can set the animations through the CSS."

You’re requesting a "check within viewport" utility so you can manage animations manually—yet ScrollReveal allows you to create and manage animations dynamically through JavaScript, so you don’t have to manage them manually.

Luckily, there are already a number of libraries available that determine if an element is within the viewport. I have not used this one but [Within Viewport](https://github.com/patik/within-viewport) seems suited to the task. Here’s some pseudo code how it might work:

```js
// create a node list of the elements you want to watch
var elements = document.querySelectorAll('.foo');

// define an event handler (for use with scroll or resize)
function visibilityHandler() {
  // use requestAnimationFrame to throttle scroll events
  window.requestAnimationFrame(function(){
    for ( var i = 0; i < elements.length; i++ ) {
      if ( withinviewport( elements[i] ) ) {
        elements[i].classList.add('.animationClass');
      }
    };
  });
}

// light it up!
window.addEventListener( "scroll", visibilityHandler );
window.addEventListener( "resize", visibilityHandler );
```

For fun, you could very well create this utility yourself in less than 100 lines of code by referencing the ScrollReveal source ([line 308](https://github.com/jlmakes/scrollreveal.js/blob/master/scrollreveal.js#L308) to [393](https://github.com/jlmakes/scrollreveal.js/blob/master/scrollreveal.js#L393)).

Hopefully this points you in the right direction! :bow:
