### ISSUE TITLE
Sequenced Animation

### ISSUE THREAD

**Issue by TiagoDeSousa** [jlmakes/scrollreveal.js#240]
When I set a sequenced animation as so:
```js
window.sr = ScrollReveal();
sr.reveal( '.animate', { delay: 700, easing: 'ease', duration: 800, scale: 0 }, 200 );
```
It actually animates as it should, however:
- It animates every element with the class `.animate` even if it's not in the viewport.
- If you're in the middle of the page and hit refresh the animated elements in the viewport have to wait until the previous elements animation finishes.

**Comment by jlmakes** [comment]
**This is by design.**

I went through a number of strategies, each of which were complex and flawed. You’re describing the desired effect of only revealing what is visible in sequence—but what about `config.reset`? When you scroll back up in that reality, your sequence either has broken order or has to wait (??) until you’ve finished scrolling… both of which are quite unusual. 

So maybe... reveal normally if scrolling up with `config.reset` but use the sequence when scrolling down. But what about scrolling left or right? What’s more, I’ve experimented with negative sequence intervals for reverse sequences (last to first)… which further complicates the above scenario.

After taking a step back, it became clear that the logic was only growing more and more complex (and at odds with the existing ScrollReveal source) and I needed something that worked for scrolling up, down, left or right for sequences and reverse sequences. And thus the current sequencer:

- If any element of a sequence is visible, reveal the sequence.
- If no elements of a sequence are visible, hide the all elements in that sequence.

It’s simple, and honors the fact that sequenced elements are essentially a group—and that group’s visibility is what is measured, not that of the individual elements.
