### ISSUE TITLE
offset for adjacent containers

### ISSUE THREAD

**Issue by dstN** [jlmakes/scrollreveal.js#244]
hello,

is there a possibility to give a little "scope" for the revealing items before they fade out? cause they shouldn't fade out instantly if one pixel from the next container is visible, but currently thats what happens for me.

jsfiddle: https://jsfiddle.net/5jqzqu8h/

thanks in advance!

**Comment by jlmakes** [comment]
I believe you’re referring to this...

![sr-prob](https://cloud.githubusercontent.com/assets/2044842/14195316/4ac90734-f7b8-11e5-941d-b679a1e03e35.gif)

Since _both_ libraries use scroll and position, I can’t offer you much support on how they conflict. What I can tell you is that ScrollMagic modifies `div.scrollmagic-pin-spacer` and `div#pinContainer` as soon as the "next container" begins scrolling in from the left.

Whatever ScrollMagic does to this "pin" breaks ScrollReveal’s capacity correctly ascertain the visibility of those elements. Perhaps you can experiment with the styles that ScrollMagic is adding to find what is breaking things.

@dstN :bow:

**Comment by dstN** [comment]
do you think thats also the problem why scrollreveal reveals elements which are not in the view?

cause in this fiddle: https://jsfiddle.net/330yjowy/ 

i added content on the dark-grey-section (.scenecontainer.third) and wanted to reveal it as well if it scrolls into view, but it already reveals the elements if the first three blocks on the .scenecontainer.second-section getting revealed.

**Comment by jlmakes** [comment]
Inspect the source...

ScrollReveal isn’t revealing anything that's not already within the viewport… but ScrollMagic is using `position: fixed` and `transform: translate()` to _emulate_ scrolling for those "pinned" regions.

The simple fact is that ScrollReveal uses the browser’s native scrolling to work, and any library that breaks that is almost guaranteed to break ScrollReveal.

**Comment by dstN** [comment]
thank you for your answer. and yes, you are right. just realized that, and just used ScrollMagic itself to let the content appear with velocity.js

**Comment by dstN** [comment]
and now i just throw ScrollMagic out of the document cause your plugin is way smoother than this.. or i am too dumb. :) thank you anyway!
