### ISSUE TITLE
Trouble with installation/usage on Joomla Yootheme template

### ISSUE THREAD

**Issue by Arturo-Cortes** [jlmakes/scrollreveal.js#245]
- Operating system: `OSX 10.10.5`
- Browser: `Firefox 45.0.1`
- ScrollReveal: `3.1.4`

Hello,
We where using scrollreveal.js 2.3 with joomla 3.4 and yootheme sixth avenue template and it was working perfectly. The instalation process and usage was easy in previous versions as some user pointed out previously. However at some point scrollreveal.js stoped to work, we suspect it happened when we upgraded to nevest version of yootheme sixth avenue template but we are not sure about it.

To solve this we have decided to upgrade to nevest 3.1.4 version of scroll reveal but now installation is more confuse so I would like to ask how the explanation can be easier for more beginners like us.

#### Where do scripts go?

When you explain functionality in 1.2.THE BASIC we understand that the following part should go inside of HTML page, this part seems clear

```html
<!-- HTML -->
<div class="foo"> Foo </div>
<div class="bar"> Bar </div>
```

But we have doubt where javascript ( pardon for our ignorance) should go?

```javascript
window.sr = ScrollReveal();
sr.reveal('.foo');
sr.reveal('.bar');
```
Previously we added this inside of template `theme.php` along with scrollReveal.js installed inside of js folder and it worked, but now it does not work anymore so we have that doubt where this code should be placed.

We have also tried to copy paste the snippet inside of `theme.php` and it does not work either:
```html
<script src="https://cdn.jsdelivr.net/scrollreveal.js/3.1.4/scrollreveal.min.js"></script>
```

#### Incompatibility?

Can possibly be there any incompatibility with other elements like php, javascript or other element to cause this problem even if the installation is done correctly?

Thank you for your help!
Arturo Cortés :bow:

**Comment by jlmakes** [comment]
#### Where do scripts go?

The placement of the script is outlined in the [README Section 4](https://github.com/jlmakes/scrollreveal.js#4-tips)—but since you are using Joomla, you would need to review it’s documentation (and perhaps that of the theme you’re using) to find the appropriate place for custom scripts.

#### Differences between v2 and v3

ScrollReveal 2 used an inline API, for example:
```html
<div data-sr="enter top over 2s"> Hello </div>
```

Whereas ScrollReveal 3 uses a more flexible JavaScript API, for example:
```html
<!-- HTML -->
<div class="foo"> Foo </div>
<div class="bar"> Bar </div>
```
```js
// JavaScript
sr.reveal('.foo');
sr.reveal('.bar');
```

You can check out the [discussion from issue 194](https://github.com/jlmakes/scrollreveal.js/issues/194) for more information on why, but to put it simply, ScrollReveal 3 is not a drop in replacement for version 2… it is a critically breaking upgrade.

***

So @Arturo-Cortes, as you can see, if your theme uses version 2, you should stick with version 2 unless you’re prepared for the migration, but... I looked at the theme briefly, and I don’t see any ScrollReveal effects. **The simplest answer is that they no longer use ScrollReveal.**
