### ISSUE TITLE
Items not revealed upon page load using Angular

### ISSUE THREAD

**Issue by marko911** [jlmakes/scrollreveal.js#247]
I'm trying to use scrollReveal in a partial on a `<li class="media-entry">` which runs inside of a `ng-repeat`. The problem is the items selected don’t get revealed on page load. They are there but still hidden.

I've injected 
```html
<script>
    window.sr = ScrollReveal();

    if (sr.isSupported()) {
        document.documentElement.classList.add('sr');
    }
</script>
```

```html
<style>
    /* Ensure elements load hidden before ScrollReveal runs */
    
    .sr .media-entry {
        visibility: hidden;
    }
</style>
```

Into the header of my `index.html`. I also added the following right before closing body tag: 
```html
<script>
    sr.reveal('.sr.media-entry');
</script>`
```

This is the code in my controller:
```js
$scope.$on('$viewContentLoaded', function () {
    sr.reveal('.sr.media-entry');
});
```

What am I missing? Why aren't the items being shown?

**Comment by jlmakes** [comment]
First off, you don't need `sr.reveal('.sr.media-entry');` twice.

Secondly, the reason your elements are hidden is likely because of the `visibility: hidden` style, not because of any initialization by ScrollReveal.

You mentioned in a previous issue that only 1 element was returned when you examined `sr.store.elements` in the console—which means ScrollReveal is not running after your `ng-repeat` has compiled. **Using the `$viewContentLoaded` event worked for me in my testing, but I was not using ScrollReveal inside a directive.**

What’s more, it’s not recommend to interact with the DOM within a controller. I recommend looking into running code after the compile phase of ng-repeat using a directive, for example:
[StackOverflow: ng-repeat finish event](http://stackoverflow.com/questions/13471129/ng-repeat-finish-event)

**Comment by marko911** [comment]
Thanks for your help, I will follow your advice and let you know the result. Cheers.

**Comment by marko911** [comment]
I've turned it into a directive and it works but only on the visible elements, the elements that come after you scroll down stay hidden. The directive calls reveal on the last element of the ng-repeat like you suggested but that last element isn't visible when the page loads. I have 18 list items load and only the first 9 are visible on page load. Those 9 have the scrollReveal effect when the page loads, as soon as I scroll down , the rest are invisible.

**Comment by jlmakes** [comment]
@marko911 If you add a container, that _doesn’t_ have a fixed height and `overflow-y: scroll` then all elements will be animated immediately. So your second edit makes sense. (In fact in that scenario, if you scroll down fast enough you should seem them animating too.)

Have you tried setting `html, body { height: 100%; }` in your CSS? I’m curious what’s causing the odd behavior with the default container, any way you can upload the progress for me to take a look?

**Comment by marko911** [comment]
The project is pretty big for my standards lol so I will create a new repo and upload it after I try the css suggestions.

**Comment by marko911** [comment]
Alright, finally got it working. Yea the container just needed overflow-y:auto and height :100% and it works now. So the last thing is setting each individual ng-repeat element to have a different animation setting. I'm thinking of adding an id to each one and then randomly generating a config object for each and then when the directive fires the reveal it will actually loop through and call reveal for each id...Any better/more elegant recommendation for this ?

**Comment by jlmakes** [comment]
Well, `reveal()` accepts element DOM nodes as the first argument, not just selectors… and you already have a reference to each element as ng-repeat compiles...

```js
// the previous example...

angular.module('myApp').directive('ngRepeatReveal', ngRepeatReveal);

function ngRepeatReveal() {
    //                        here                                        
    //                         ↓
    return function (scope, element, attrs) {
        if (scope.$last){
            sr.reveal('.media-entry');
        }
    };
}
```

But I believe it’s a reference to an Angular element, so I would attempt something like this...

```js
angular.module('myApp').directive('ngRepeatReveal', ngRepeatReveal);

function ngRepeatReveal() {
    //                        here                                        
    //                         ↓
    return function (scope, element, attrs) {
        
        // get raw node from angular element
        var el = element[0];

        // generate a random config, here’s just
        // a simple example...

        var config = {
            distance: (20 * Math.random()) + 'px',
            duration: (2000 * Math.random())
        };

        // reveal the element with it’s own config
        sr.reveal(el, config);
    };
}
```

This is an untested concept, but hopefully this points you in the right direction. Good luck! :bow:

**Comment by marko911** [comment]
@jlmakes Is there any way to make scrollReveal work on containers that have an auto height?

**Comment by jlmakes** [comment]
@marko911 The default value for `height` is `auto`. There is no overflow, and there is no scroll. What you're asking isn’t possible since ScrollReveal relies on scroll.

If you are trying to create a specific effect, you can open a new issue describing it and I can try to help. Also, the README contains comprehensive documentation on essentially every feature of ScrollReveal.

🐝
