### ISSUE TITLE
Multiple instances of ScrollReveal

### ISSUE THREAD

**Issue by DMouroutis** [jlmakes/scrollreveal.js#256]
I am using ScrollReveal 3.1.4 and I cannot manage to work with multiple instances of  the object.

I've already saw the issues https://github.com/jlmakes/scrollReveal.js/issues/129 and https://github.com/jlmakes/scrollReveal.js/issues/61, but my error still exists.

I use the following code written below and only the foo instance is valid and works.
( if i remove the foo initialization, the sr object works properly then)

```js
// Sr
window.sr = new ScrollReveal({ mobile: false });
sr.reveal( '.brands-grid-item img', fooReveal );
sr.reveal( '.brands-grid-item h4', fooReveal );
sr.reveal( '.brands-grid-item span', fooReveal );

// Foo
window.foo = new ScrollReveal({
    viewport: document.getElementById('popup-window'),
    mobile: false
});
foo.reveal( '.text-wrapper', fooReveal );
foo.reveal( '.video-wrapper', fooReveal );
```

**Comment by jlmakes** [comment]
@DMouroutis The problem is that the first instance never gets initialized (try inspecting `sr` in the console). I’m not 100% on this, but recent experiences have lead me to believe that closure scopes continue to exist (instead of being recreated), so in other words...

I believe it’s because `this` is aliased as `sr` internally (so ScrollReveal can reference itself easily), so when you instantiate a second time, `sr` points to the 2nd instance… which is why the first instance will correctly prepare elements for reveal (generate styles and hide them), but is "disconnected" before initialization because of the 2nd instance.

#### So what does that mean?

Previous versions of ScrollReveal poorly handled multi-instances because of tight coupling with the DOM and the lack of a JavaScript API. Since you’re using the latest version though, there shouldn’t be a need for a second instance.

I don’t know what you included in `fooReveal`, but I’ll pretend it was `move: 10px` for demonstration:

```js
window.sr = new ScrollReveal();

var fooReveal = {
  move: '10px',
  mobile: false
}

sr.reveal( '.brands-grid-item img', fooReveal);
sr.reveal( '.brands-grid-item h4', fooReveal);
sr.reveal( '.brands-grid-item span', fooReveal);

var barReveal = {
  move: '10px',
  mobile: false,
  viewport: document.getElementById('popup-window')
};

sr.reveal( '.text-wrapper', barReveal);
sr.reveal( '.video-wrapper', barReveal);
```

In all cases I can imagine, you should only need one instance of ScrollReveal since you can pass any configuration you want to the `reveal()` method. Did you have something specific in mind that you aren't able to do with one instance?

**Comment by DMouroutis** [comment]
I came to the same conclusion because of the uninitialized first instance.

I wanted to have scrollReveal setup on my page and a 2nd instance of sr for a fixed popup window that will track any further scroll movement to reveal the contents within.

I did not know about viewport parameter in reveal function, I will try that configuration and let you know about the results.
