### ISSUE TITLE
Trouble with overflow on mobile

### ISSUE THREAD

**Issue by ninoCookies** [jlmakes/scrollreveal.js#261]
Hello, 

I'm using ScrollReveal with Foundation 6 from ZURB. Problem I've noticed is that if I use ScrollReveal on the mobile version of my website, I get the "horizontal" scroll option - even though there is no content wider then the mobile screen.

Of course I've tried fixing that by using:
```css
body, html {
  overflow-x: hidden;
}
```
After that scroll reveal stopped working completely - to the extent where the content wouldn’t get loaded at all. Any ideas ?

**Comment by jlmakes** [comment]
@ninoCookies I can help you troubleshoot, but I will need a lot more information about your setup. Can you link me to a live version of the problem? (Either JSBin or a link to your site will work)

**Comment by ninoCookies** [comment]
I'm sorry - i've missed your response back in June.
Page is www.examfit.eu  - issue is visible on first page on mobile.

**Comment by jlmakes** [comment]
@ninoCookies I don’t see why ScrollReveal would be adding any horizontal width, since I couldn’t find any animations that come in from the side. _I don’t think this problem is caused by ScrollReveal._

However, here’s what I found...

### The Offending DOM Element

![screen shot 2016-07-09 at 12 35 02 pm](https://cloud.githubusercontent.com/assets/2044842/16707518/c4fd1326-45d1-11e6-95c9-4fc435d465bf.png)

### The Offending Layout Bug

![2016-07-09](https://cloud.githubusercontent.com/assets/2044842/16707526/126558da-45d2-11e6-8f55-2f62ef327b66.png)

**Comment by ninoCookies** [comment]
You are completely right. 
The reason why i was thinking ScrollReveal is causing the issue is due to overflow:
`body, html {
  overflow-x: hidden;
}`

This code "fixed" my horizontal scroll but broke the ScrollReveal - so i assumed wrong. 
After that i went trough whole page with Chrome inspect - and it did not show me the overflow width of this button as your screenshot does....

Thank you for your extended help, lets close this :dancer:

**Comment by jlmakes** [comment]
@ninoCookies I plugged up my iPhone to my Mac, and opened the debugger. Just started deleting DOM nodes until the problem went away, which showed me which DOM node contained the problem. Drilled down, and saw the offending element.
