### ISSUE TITLE
FYI:  Reason for why it never shows.

### ISSUE THREAD

**Issue by ensemblebd** [jlmakes/scrollreveal.js#271]
This is in reference to: https://github.com/jlmakes/scrollreveal.js/issues/125
Exact same issue, but completely different reason.

Primary cause is when the container element uses % height. Fluid layouts (basically any responsive framework now days), have a standard setup with `html, body {height: 100%}`
Therefore the height of the document is the height of the screen (aka body has height of 800, but content goes well over 3000). 
Therefore **_isElemVisible** ALWAYS returns false for anything below the viewable region of the screen.
Which leads to an opacity always being zero.

I stepped through it with the debugger, and determined that with interval not specified, the function to reveal or reset is never called.
If interval is specified, it instantly performs it's callback, causing and instantaneous reveal and reset, so fast the animation doesn't even take place - aka invisible.

So the correct thing to do in this scenario, is specify a container that actually has a size, via clearfix or what have you. That way the logic isn't broken in this script. The default value of document, or choosing body, isn't necessarily safe whatsoever.

While I believe this is something you should fix as an improvement, I realize the easier solution would be to add some documentation on that front. Thanks for your consideration on this issue, as well as all your efforts on this great project

See Also:

1. http://stackoverflow.com/questions/12788487/document-scrolltop-always-returns-0
2. http://stackoverflow.com/questions/1830080/jquery-scrolltop-doesnt-seem-to-work-in-safari-or-chrome-windows

**Comment by jlmakes** [comment]
Thanks for this @ensemblebd, very cool. Is there a live demo you point me to that will show this problem happening? [I tried to recreate this](http://jsbin.com/tilolaq/edit?html,css,output) as I have in the past, and my results appear to work as expected.

What am I missing?

**Comment by ensemblebd** [comment]
ahh cool so I think I was on the right track there. I started using that (checked for zero, and compared), but couldn't get it to work properly in the _getBounds. 

Perhaps this was a chrome version issue, I'll do so more testing and confirm whether it's consistently happening. And setup a demo of this on jsfiddle to test out as well. Will report back a little later today. Thank you for your insight and assistance!

**Comment by ensemblebd** [comment]
See the issues:
https://jsfiddle.net/4fbyp787/14/

It has X framework (wordpress) running, as well as Zurb Foundation v6, and jquery-ui.
process of elimination led me to the cause:
` html {
   overflow-x: hidden;
 }
 body {
   overflow-x: hidden;
 }`

See the fix:
https://jsfiddle.net/4fbyp787/15/
`body {
   overflow-x: initial;
 }`


So I am unsure what the resolution really is. Why would chrome respond so terribly when you hide horizontal scrolling on a full width page? It seems to lose all of it's logical faculties in regards to offsets and scrolling, when the overflow-x: hidden.
Any ideas?

**Comment by jlmakes** [comment]
I’m having a hard time breaking down those fiddles. I’m still not entirely clear on what the issue is, when/where it happens and why.

One thing that stands out however, is how you’re using containers. Figure 1 below shows the setup you have created in the fiddles above.

_Figure 1:_
![Incorrect use of container](https://cloud.githubusercontent.com/assets/2044842/16802104/f933f4fe-48fe-11e6-8335-640cf353a6b2.png)

In this situation, you don’t actually want to use a custom container — because the container itself has no scrollbar, and thus no scroll events to bind to. Elements will always be visible, since relative to their container, they are always visible.

What we need is a fixed height container with overflown content (vertical or horizontal) for ScrollReveal to work. Let’s refactor Figure 1’s container with this in mind:

_Figure 2:_
![Correct use of container](https://cloud.githubusercontent.com/assets/2044842/16802359/a08b5ce6-4900-11e6-8de2-9137fd2663ef.png)


Here you can see that our main website has a fancy layout. Since here the container has a fixed height and scroll bar, ScrollReveal can work with this setup.

**Comment by jlmakes** [comment]
What I need if I am to fix/improve anything, is the simplest possible demonstration of the issue. As it stands, I’m not 100% clear on what behavior I should be seeing, and what behavior is expected.

**Comment by ensemblebd** [comment]
Great information!!! I appreciate this greatly, and it explains the problem perfectly. For the moment I think it can be considered a non-issue. The framework I'm using naturally uses the first type of document flow, so it will be a problem for that framework, but that's a use-case issue. I'll play with it some more and if I can locate something to improve this scenario for this type of scenario, will make a pull request on it. 

Again, amazing plugin, and stellar support, wishing you a great day!

**Comment by jlmakes** [comment]
Cheers mate, thanks for all your effort. 👍🏾
