### ISSUE TITLE
Begin reveal only when previous sibling has revealed

### ISSUE THREAD

**Issue by midaspider** [jlmakes/scrollreveal.js#272]
Hello, I'm using v3.2.0.

I've found the recent feature enabling you to add a delay to each item, creating a sequence which means that all items in that group will reveal one at a time as soon as one of them is in view.

Lets say for example you have a group of 20 items, the items are arranged in a grid set to wrap. Depending on view width they are arranged so that 2, 3 or 4 make up a row. Currently I can either have them all sequentially reveal as soon as one is in view OR I can have all items in each row reveal at the same time as they come into view.

What I want to achieve is for only those 2, 3 or 4 items that come into view (each row) to reveal sequentially, the next rows would remain hidden until they come into view, is this possible?

**Comment by jlmakes** [comment]
The short answer is no.

When initially creating the sequencer, I worked on this very idea. The problematic details escape me at the moment, but I recall it being deceptively challenging to handle the edge cases.

I had to take a step back and focus on a simplified concept that addressed the essence of the sequencer — to save developers time when revealing a few items in a row, since it's such a common use case.

The deeply configurable sequencer I initially imagined is something I want to revisit for the next major rewrite, when I can integrate it into the bedrock instead of backing into it.

**Comment by nunaram** [comment]
I was looking for this kind of reveal animation for sequenced items.

**Comment by jlmakes** [comment]
@nunaram @midaspider You know, this could probably be set this up using ScrollReveal’s callbacks… I’ll play around with it and post a demo a bit later.

**Comment by midaspider** [comment]
Thanks for the reply and the plugin, I like the simplicity and the reliable feel of it so will use the plugin as it is.

Just a bit of rubbish pseudo code below but would it be something along these lines?

```
itemsToReveal = $('itemInView');
var indexItem = 0;
if (itemsToReveal > 1 && stagger == true) {
setInterval(function() {
    itemsToReveal[indexItem++ % itemsToReveal.length];
    indexItem.addClass('reveal');
}, 500);​
}
```

I guess you would need to write the plugin to initially check how many items have been scrolled to before it does anything about revealing any of them?

Also, I take it that this plugin adds inline styles to do the animations, would it be possible to have an option to use styles OR classes to decide how the animations happen? (sorry, this is an elaboration outside the scope of my initial question).

**Comment by jlmakes** [comment]
@midaspider Let me see if I can offer some help.

First I’d like to make a distinction: ScrollReveal’s sequencer uses the sequence interval (not reveal duration) to check if the next item should reveal. The solution below uses callbacks, so it requires an element complete it’s reveal before the next begins.

With that said, on to the code...

_Example:_

```js
// Using recursion, we reveal an element and set it’s callback
// function to invoke the same function again. Notice that we are
// using ++ to increment the next value for the following call.
function revealNextInSequence (sequence) {
  if (sequence.next < sequence.elements.length) {
    sr.reveal(sequence.elements[sequence.next++], {
      afterReveal: function () {
        revealNextInSequence(sequence)
      }
    })
  }
}

// This process is started by this function, which accepts
// a selector and creates a "sequence" object with it to pass
// to our `revealNextInSequence` method.
function startSequence (selector) {
  var sequence = {
    elements: document.querySelectorAll(selector),
    next: 0
  }
  revealNextInSequence(sequence)
}

// Here we are starting a new sequence, and passing the
// selector we wish to use.
startSequence('.mySequencedElems')
```

### See the [Live Demo on JSBin](http://jsbin.com/tipiqo/edit?js,output)

*Important Note:* I am using `visibility: hidden` on all of the `.mySequencedElems` so that they load hidden — awaiting ScrollReveal to make them visible. This is a recommended best practice in the Documentation, section [4.2. Tips: Improve User Experience](https://github.com/jlmakes/scrollreveal.js#42-improve-user-experience)... but in the example above, it is _required_ for the correct effect.

**Comment by midaspider** [comment]
@jlmakes
That is fantastic, it works in exactly the way I was asking about. I like the way you split the function into two parts, makes it easier to follow (and reuse I suppose).
Thanks very much!

I changed the CSS slightly to show how it still staggers when more than one item appears in view at a time.
```
html {
  /*height: 5000px;*/
  background: #eee;
}

.mySequencedElems {
  background: #fe8800;
  border-radius: 10px;
  color: white;
  font-family: sans-serif;
  font-weight: 700;
  font-size: 300%;
  text-align: center;
  line-height: 100px;
  height: 100px;
  margin-bottom: 10px;
  visibility: hidden;
  width: 32%;
  display: inline-block;
}
```
Can I ask why you set a height on the body element, it seems to work perfectly with it removed.

**Comment by jlmakes** [comment]
@midaspider Oh that's nothing.

Before I setup the sequence… I was confirming that the change in `viewFactor` was working correctly, which I did using only 1 element; the `height: 5000px` was merely to force the window to scroll so I could play with reveal/reset on the element.

Cheers! 🍻

**Comment by DoyinDimeji** [comment]
<a href="https://facebook.com">holla</a>
