### ISSUE TITLE
Reset only when element is completely outside viewport

### ISSUE THREAD

**Issue by tofuness** [jlmakes/scrollreveal.js#274]
_Running ScrollRreveal 3.2.0 on Chrome 51 (Windows 10)_

I would love some guidance on how I can have `viewFactor` at `0.7` but only trigger `reset` after the element is completely outside the viewport.

Thanks!

**Comment by jlmakes** [comment]
#### I put together a demo for you → [View on JSBin](http://jsbin.com/hikaroq/edit?js,console,output)

_For Posterity:_
```js
window.sr = ScrollReveal();

var minVFactor = 0.0;
var maxVFactor = 0.3;

sr.reveal('.foo', {
  reset: true,
  viewFactor: maxVFactor,
  afterReveal: setMinVFactor,
  afterReset: setMaxVFactor
});

console.log("vFactor initialized as: " + maxVFactor);

// ScrollReveal callbacks are passed
// the dom element, so it’s easy to
// pass this to our setVFactor() method
// which re-reveals that element with
// the new configuration.

function setVFactor (el, vf) {
  sr.reveal(el, { viewFactor: vf });
}

// And the callbacks themselves...

function setMinVFactor (el) {
  setVFactor(el, minVFactor);
  console.log("vFactor set to: " + minVFactor);
}

function setMaxVFactor (el) {
  setVFactor(el, maxVFactor);
  console.log("vFactor set to: " + maxVFactor);
}
```

I’ve included a few `console.log()` to help demonstrate how/when this works. The caveat to this solution is that if you scroll up immediately after a reset triggers, there can be a bit of delay depending on your settings.

When #273 is implemented, this delay should be removed by the theoretical `resetStart` callback instead of `afterReset.

#👍🏾

**Comment by tofuness** [comment]
Thank you so much @jlmakes ! Closing this issue.
