### ISSUE TITLE
Lack of Firefox transition/transform support

### ISSUE THREAD

**Issue by rae0724** [jlmakes/scrollreveal.js#282]
Hi, I am using ScrollReveal 3.3.1.
My div is using css animation when mouseover/hover.
But after I put on the scrollreveal on it.
The hover animation which I put on myself not working anymore.
Because the plugin overwrite it with its own "transition"
I checked on chrome, it apply "transition" and "-webkit-transition".
Is there anyway I can add on "-moz-transition" too?
Thank you.

**Comment by jlmakes** [comment]
I believe this is related to #251.

Right now @rae0724, ScrollReveal should retain existing CSS Transitions on revealed elements, and it shouldn’t need `-moz-transition`… Firefox has supported un-prefixed transitions for quite some time.

However, ScrollReveal _does not preserve CSS Transforms_. I think this is the issue you’re running into — and this is a going to be fixed in the next release.

The current work around is to just wrap your elements in a`div` and use ScrollReveal on that element instead.

**Comment by rae0724** [comment]
Yes, thank you very much for your explanation :)
I will use div to wrap it first ^^ thank you
will wait for the next release
