### ISSUE TITLE
overflow bug - confirmBounds() error

### ISSUE THREAD

**Issue by studio404pl** [jlmakes/scrollreveal.js#283]
Hi, 

I've found a bug related to elements that have `overflow-x:hidden`.

For example, I have an image that has a negative `margin-left` and the function `confirmBounds()` returns these values for left offset and view factor:

`left: -7`
`viewLeft: 0`

That image is wrapped in div with `overflow-x:hidden`.

The return condition in that function will return always false, and the element is hidden since it's not placed completely in viewport area. ViewFactor setting is pointless in that case.

IMHO that function should not check for all sides view factor cause in my case only left edge is not visible in viewport. ViewFactor should check for at least one or two edges, not for all.

**Comment by jlmakes** [comment]
Are you using ScrollReveal on the wrapper div, or the image element?

**Comment by studio404pl** [comment]
on the image element. I have two elements in that wrapper.. one slides from left and another one from right.

**Comment by jlmakes** [comment]
Hmm, so part of the image is off of the canvas? If so, you can reduce the view factor, so that if any amount of an element is within the viewport it is considered visible. By default, 20% of an element must be visible to be considered visible.

If you have some sample code I can take a look at, I will gladly help you debug.
