### ISSUE TITLE
Problem with position: fixed

### ISSUE THREAD

**Issue by pdoan-tsr** [jlmakes/scrollreveal.js#285]
Asuming I have the structure 
```html
<div class="row" data-sr="....">
 <div class="medium-6 columns">
 <div class="medium-6 columns fixed">
</div>
```

The fixed class has the fixed position attribute.
When using ScrollReveal with fixed position, this attribute is obselete / has no effects. It is possible to use both together?

Thanks

**Comment by jlmakes** [comment]
You're using ScrollReveal on a containing div, which will not impact the fixed child inside the way you expect. You will need to use ScrollReveal directly on the fixed element.

Also, if you are using `data-sr`, that means you are using an unsupported version of ScrollReveal. I would recommend looking at the version 3 changes, since it provides a powerful JavaScript API, a ton of bug fixes and is actively supported.
