### ISSUE TITLE
Using with Masonry

### ISSUE THREAD

**Issue by br0k3n** [jlmakes/scrollreveal.js#286]
Hi, using this plugin with a masonry layout it doesn't work till we resize the browser window.
It could be related with the absolute position of all elements?

Here's the link: http://goo.gl/jLGLkU

Thanks

**Comment by jlmakes** [comment]
There's a good chance it's the order causing the problem.

Look at these [Masonry Events](http://masonry.desandro.com/events.html), you'll want to call ScrollReveal inside these callbacks -- that way, whatever positioning and styles Masonry generates, ScrollReveal will simply be building on top of it (instead of competing).

Let me know if this helps.

**Comment by br0k3n** [comment]
Hi, thanks so much, I test it but it doesn't works, here's the code used:

`function masonryBlogHeight() {
			var maxHeight = -1;
			$('.thmlvMasonryBlogWrap').each(function() {
				maxHeight = maxHeight > $(this).height() ? maxHeight : $(this).height();
			});
			$('.thmlvMasonryBlogWrap').each(function() {
				$(this).height(maxHeight);
			});
}		
		
		function masonryBlogInit() {
			if($('.thmlvIsotopeBlogVC').length > 0) {
				masonryBlogHeight();
				var $window = $(window);
				var $container = $('.thmlvIsotopeBlogVC');
				$container.imagesLoaded(function() {
					$container.isotope({
						itemSelector: '.thmlvMasonryBlogVC',
						percentPosition: true,
						masonry: {
							// use outer width of grid-sizer for columnWidth
							columnWidth: '.thmlvMasonryBlogVC'
						}
					});
					$container.isotope('on', 'layoutComplete', function (isoInstance, laidOutItems) {
						window.sr = ScrollReveal().reveal('.thmlvMasonryBlogVC');
					});
				});
			}
		};
		masonryBlogInit();
		
		$(window).resize(masonryBlogInit);`

Please, could you help us?

Thanks so much :)

**Comment by Honza-B** [comment]
Hi, at first change

`$(window).resize(masonryBlogInit);`

 to:

`$(window).resize(function () {
     masonryBlogInit();
});`

I hope it will help :-)

**Comment by jlmakes** [comment]
I'm not that familiar with your code base or Masonry, but I did spot one thing @br0k3n:

`window.sr = ScrollReveal().reveal('.thmlvMasonryBlogVC');`

There's no need to re-assign the `sr` variable to a new instance of ScrollReveal _every time the layout complete event fires_.

In fact, I would suspect it causes problems because the element store (which contains all the animation data) gets erased each time, but the corresponding element IDs (which are stored as `data-sr-id` attributes) will remain on the elements.

This means that those IDs no longer reference the element store correctly... So when ScrollReveal goes to find the styles and animation information for `data-sr-id="1"` it's going to look in the element store, and it won't find what it's looking for.

Instead, what I recommend is to only instantiate ScrollReveal once.

```js
// don't do this...
// window.sr = ScrollReveal().reveal('.thmlvMasonryBlogVC');

// do this...
if (!sr) {
  window.sr = new ScrollReveal();
}
sr.reveal('.thmlvMasonryBlogVC');
```

I'm not sure if this will fix all the issues surrounding your project, and combining ScrollReveal with Masonry, but this should definitely help get you closer -- and serve as good advice for when using ScrollReveal the future.

**Comment by jlmakes** [comment]
Also @br0k3n,

I've provided some code notes and suggested code refactoring:

```js
function masonryBlogHeight() {
	var maxHeight = -1;
	// you reference the same jQuery selector twice,
	// making jQuery search for the same element twice.
	$('.thmlvMasonryBlogWrap').each(function() {
		// this line is simply returning the larger of 2 values,
		// but JavaScript has a built in math library for this.
		maxHeight = maxHeight > $(this).height() ? maxHeight : $(this).height();
	});
	// I'm not sure what the significance of calling this the
	// second time...
	$('.thmlvMasonryBlogWrap').each(function() {
		// This line could just be moved into the first `each` above.
		$(this).height(maxHeight);
	});
}
```

Which could be written as:
```js
function masonryBlogHeight() {
	$('.thmlvMasonryBlogWrap').each(function() {
		var maxHeight = Math.max(-1, $(this).height());
		$(this).height(maxHeight);
	});
}
```

I'm not sure what the significance of applying an element's height to itself again is (since I assume it will always be bigger than `-1`) but this _should _ get the job done.

**Comment by jlmakes** [comment]
What is the point of this code @br0k3n?

```js
function masonryBlogHeight() {
	var maxHeight = -1;
	$('.thmlvMasonryBlogWrap').each(function() {
		maxHeight = maxHeight > $(this).height() ? maxHeight : $(this).height();
	});
	$('.thmlvMasonryBlogWrap').each(function() {
		$(this).height(maxHeight);
	});
}	
```

It appears to set the height of an element to it's own height... which regardless of the reason, could be simplified using JavaScript's built-in `Math` library.

```js
function masonryBlogHeight() {
	$('.thmlvMasonryBlogWrap').each(function() {
		var maxHeight = Math.max(-1, $(this).height());
		$(this).height(maxHeight);
	});
}
```

**Comment by DerekBess** [comment]
@jlmakes Just wanted to thank you for your advice as I was able to get this working with Masonry by following your input.

This is what I have in my project and it works as expected.

```
(function($) {

    function masonryGridInit() {
        
        // Grid Container
        var gridContainer = $('.masonry-grid');

        // Grid Options
        var gridOptions = {
            itemSelector: '.brick',
            columnWidth: '.grid-sizer',
            gutter: '.gutter-sizer',
            percentPosition: true,
            transitionDuration: '0.2s'
        };

        // layout Masonry after each image loads
        gridContainer.imagesLoaded(function() {
            gridContainer.masonry(gridOptions);
            
            // Bind Event Listener To Layout
            gridContainer.masonry('on', 'layoutComplete', function () {
                // Init Scroll Reveal
                if (!sr) {
                    window.sr = new ScrollReveal();
                }
                sr.reveal('.card');
            });
        });
    }

    // Init Masonry Layout 
    $(window).on('load resize scroll', function(e){
        masonryGridInit();
    });

}(jQuery));
```
